services:
  kitchen-1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        config: config-1
    ports:
      - "8080:8080"
  kitchen-2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        config: config-2
    ports:
      - "8082:8082"
  kitchen-3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        config: config-3
    ports:
      - "8084:8084"
  kitchen-4:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        config: config-4
    ports:
      - "8086:8086"
